### ISSUE TITLE
Usuario en lista de eventos

### ISSUE THREAD

**Issue by fblupi** [fblupi/grado_informatica-DIU#16]
Cuando es el usuario el organizador, debería aparecer éste y no "Usuario normal".

![captura](https://cloud.githubusercontent.com/assets/6973564/11767462/937aa510-a1ae-11e5-9e5f-799a30252c1b.PNG)

**Comment by louri91** [comment]
Pero es que el administrador puede ver todos los eventos y ese usuario normal es el "nombre" del usuario que lo organiza jajaja, como si pone "Rodrigo Pérez"

**Comment by louri91** [comment]
No he dicho nada, había leído mal, pero aun así es que ese es su nombre jaja

**Comment by fblupi** [comment]
Es verdad, fallo mio, cierro esto.
