### ISSUE TITLE
Imagen no se ajusta al carrusel

### ISSUE THREAD

**Issue by fblupi** [fblupi/grado_informatica-DIU#2]
Cuando la pantalla es muy grande, la imagen del carrusel no se ajusta al contenedor
![captura](https://cloud.githubusercontent.com/assets/6973564/11598223/e8cf9510-9ac0-11e5-89a9-d5db4812ee4f.PNG)

**Comment by louri91** [comment]
Pero eso es por tu pantalla! Ya te dije que en pantallas más grandes fallaría jajaja. Me inventaré algo con el css 👻
