### ISSUE TITLE
Lista de empresas no centrada

### ISSUE THREAD

**Issue by fblupi** [fblupi/grado_informatica-DIU#20]
En la lista de empresas no aparece un elemento encima de otro
![captura](https://cloud.githubusercontent.com/assets/6973564/11785722/666d71b2-a283-11e5-8ca6-42b98eb6e02f.PNG)

**Comment by louri91** [comment]
![captura de pantalla 2015-12-15 a las 9 40 57](https://cloud.githubusercontent.com/assets/9786318/11805939/f78d9af0-a30f-11e5-88d7-cfe2e101af97.png)
