### ISSUE TITLE
Script de cancelar reserva de sala

### ISSUE THREAD

**Issue by fblupi** [fblupi/grado_informatica-DIU#32]
Crear script de cancelar reserva de una sala.
Para ello. Si no está asignada, se borra la entrada de la tabla alquiler.
Si está asignada mira si es de evento o empresa y busca en cuál está asignada esa sala poniendo el valor a null y borrando inmediatamente después la entrada de la tabla alquiler.

**Comment by jdanielsv** [comment]
Fran es tonto :dancer:

**Comment by jdanielsv** [comment]
:-1:

**Comment by fblupi** [comment]
:hand:
