### ISSUE TITLE
Mostrar sala en empresa

### ISSUE THREAD

**Issue by fblupi** [fblupi/grado_informatica-DIU#47]
Mostrar si la empresa tiene una sala asignada en la descripción solo si está en el rango de fechas de su alquiler. De esta forma casi no hay que hacer ni un cron para eliminarlas y sería cosa del dueño el desasignarle la sala para añadirle otra.

**Comment by louri91** [comment]
Eso lo veo un poco complicao no?

**Comment by fblupi** [comment]
habría que comprobar si la fecha actual es mayor o igual y menor o igual que la fecha que hay en el alquiler que nos da el id sala de la empresa
