### ISSUE TITLE
Editar evento por parte de Admin

### ISSUE THREAD

**Issue by fblupi** [fblupi/grado_informatica-DIU#52]
Falla porque como están en disable, sigue cogiendo los valores (que son null) e intenta editar con esos valores a lo que el servidor devuelve error. Se debería hacer algo al respecto para que no cambiase esos valores en caso de que sea admin y no sea su evento.

**Comment by louri91** [comment]
Claro, porque en vez de disable deberían ser readonly

**Comment by fblupi** [comment]
no solo eso, cuando se generan esos campos creo que se obtiene el usuario actual para organizador-usuario y sus empresas para organizador-empresa. Por lo que no aparecería en el campo el verdadero organizador. Se podría tener como disabled pero que en vez de que apareciese "No" apareciese el organizador actual. No sé si me explico.

**Comment by louri91** [comment]
Sí, es mucho más fácil, de esa forma nos quitamos los null

**Comment by louri91** [comment]
Hecho pero falta testear
