### ISSUE TITLE
Editar evento propio de un Admin

### ISSUE THREAD

**Issue by fblupi** [fblupi/grado_informatica-DIU#53]
Cuando un admin tiene también permisos de usuario puede tener eventos y en el formulario de editar evento le aparecen deshabilitados los campos de organizador cuando él podría cambiarlos.

**Comment by louri91** [comment]
Vale, si el evento es suyo si puede modificar esos campos, eso es añadir un if jejejej

**Comment by fblupi** [comment]
Si es suyo o de una de sus empresas

**Comment by louri91** [comment]
Hecho pero falta testear
