### ISSUE TITLE
Crear Empresa por parte del usuario admin

### ISSUE THREAD

**Issue by louri91** [fblupi/grado_informatica-DIU#55]
He encontrado un bug, al intentar crear una empresa con el usuario admin rellenando todos los datos bien, desconozco por qué no me funciona, me lanza "Error al crear empresa"

**Comment by fblupi** [comment]
A mi no me ha fallado. Puede ser porque le hayas puesto el mismo CIF que a otra y no pueden haber dos CIF iguales

**Comment by louri91** [comment]
Cierto, eso era lo que me fallaba jejeje
