### ISSUE TITLE
Cuando un evento se termina se desasigna el alquiler que tenía

### ISSUE THREAD

**Issue by fblupi** [fblupi/grado_informatica-DIU#67]

**Comment by louri91** [comment]
:O La única forma de hacer esto es, o bien un trigger o bien un cron en el servidor jejeje pero es fácil

**Comment by fblupi** [comment]
Por eso había puesto el "help wanted" es lo que no sabría hacer ahora mismo con seguridad. Pero bueno, como he comentado por WhatsApp, si no se hace, no pasa nada.
